### ISSUE TITLE
Fix our modal on the client side

### ISSUE THREAD

**Issue by brianek** [MissionLaunch/clean-slate#89]
@hacktoberfest 

![screen shot 2016-10-14 at 2 55 23 pm](https://cloud.githubusercontent.com/assets/9157639/19399218/646fb48e-921e-11e6-9a10-f83994c31ea6.png)
Right now our pop-up model is not showing up. Below is this code:

<div class="container">
       
        
        <div class="modal fade" id="mdTypes" role="dialog">
            <div class="modal-dialog">

                
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Eligible Misdemeanors</h4>
                    </div>

```
                <div class="modal-body">
                    <p>
                        A list of common Misdemeanors in sealing:
                    </p>

                    <div class="checkbox">
                        <label>
                            <input type="checkbox" value="">Did you inquire as to whether or not the client has an assault charge for harming
                            their ex-girlfriend or boyfriend? Assaulting their ex-girlfriend or boyfriend is a charge,
                            either a felony or misdemeanor, that is not eligible for sealing under the current law.
                        </label>
                    </div>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
```

**Comment by nickoki** [comment]
Have you added the jquery for [Bootstrap modals](http://getbootstrap.com/javascript/#modals)? 

```
$('#myModal').on('shown.bs.modal', function () {
  $('#myInput').focus()
})
```

**Comment by brianek** [comment]
Boostrap is for sure there. @nickoki. Would I have to add in jquery also?

**Comment by drewbo** [comment]
@brianek what button/text should be clicked to open the modal?

edit @jmezetin helped me find it; no problems in chrome 54, firefox 46, safari 8, and chrome 50 on android 5.0
